openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /trips/position:
    get:
      summary: "Retrieve the distance between the departure and destination"
      tags:
        - positions
      parameters:
        - name: originLatitude
          in: query
          description: "origin latitude of the trip"
          schema:
            type: number
            example: 56.3
            required: true
        - name: originLongitude
          in: query
          description: "origin longitude of the trip"
          schema:
            type: number
            example: 58.4
            required: true
        - name: destLatitude
          in: query
          description: "destination latitude of the trip"
          schema:
            type: number
            example: 45.1
            required: true
        - name: destLongitude
          in: query
          description: "destination longitude of the trip"
          schema:
            type: number
            example: 75.3
            required: true

      responses:
        400:
          description: Information in request is not correct
        200:
          description: Sent trip position
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/distance'

components:
  schemas:

    distance:
      type: string
      example:
        89.3