openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /trips/position:
    post:
      summary: "Retrieve the distance between the departure and destination"
      requestBody:
        description: Position of the trip
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/positionTrip'
      responses:
        400:
          description: Information in request is not correct
        200:
          description: Sent trip position
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/distance'

components:
  schemas:

    distance:
      type: number
      properties:
        distance:
          type: number
      example:
        distance: 89.3

    position:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      example:
        latitude: 50.849372
        longitude: 4.451009

    positionTrip:
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/position'
        destination:
          $ref: '#/components/schemas/position'
      example:
        origin:
          latitude: 50.849372
          longitude: 4.451009
        destination:
          latitude: 50.849372
          longitude: 4.451009