openapi: 3.0.3
info:
  title: ChattyCar searchTrips service
  description: Microservice handling trips searched by the user database in ChattyCar project
  version: 1.0.0
servers:
  - url: http://localhost:9005
paths:


  
