### Read one
GET http://localhost:9090/trips/1

### Read all
GET http://localhost:9090/trips

### Delete one
DELETE http://localhost:9090/trips/1

### Read all of driver
GET http://localhost:9090/trips/driver/3

### Delete all trips of driver
DELETE http://localhost:9090/trips/driver/2

### Update number of seats available
PUT http://localhost:9090/trips/inscription/3

### Calculate Distance
###Calculate Distance
POST http://localhost:9090/trips/position
Content-Type: application/json

{
  "origin":{
    "latitude": 34.32,
    "longitude": 24.09
  },
  "destination":{
    "latitude": 41.14,
    "longitude": 67.42
  }
}

### Read all with departure date
GET http://localhost:9090/trips?departureDate=2015-10-21

### Read all with origin position
GET http://localhost:9090/trips?originLat=23.45&originLon=76.43

### Read all with destination position
GET http://localhost:9090/trips?destinationLat=23.45&destinationLon=76.43

### Read all with origin and destination position
GET http://localhost:9090/trips?originLat=23.45&originLon=76.43&destinationLat=23.45&destinationLon=76.43