openapi: 3.0.3
info:
  title: ChattyCar drivers service
  description: Microservice used for drivers request
  version: 1.0.0
servers:
  - url: 'http://localhost:9004'
    description: Development server
paths:

  /drivers:
    post:
      summary: Add trip
      requestBody:
        description: Informations about the trip
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/info_trip'
      responses:
        200:
          description: Trip created, returned the trip
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/info_trip'
        400:
          description: Error

    get:
      summary: Read all the trips of the drivers
      responses:
        200:
          description: Returned list of trips
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/trip'

  /drivers/{id}:
    parameters:
      - name: id
        in: path
        description: Id of the trip
        required: true
        schema:
          type: integer

    get:
      summary: Read all the passengers for the trip (id)
      responses:
        200:
          description: Returned list of passengers of the trip
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/passenger'

  /drivers/{id}/passenger/{id}:
    put:
      summary: Change state of the passenger
      requestBody:
        description: New state of the passenger
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/state'
      responses:
        200:
          description: State changed
        400:
          description: Error

    delete:
      summary: Delete the passenger of the trip
      responses:
        404:
          description: Passenger not found
        200:
          description: Passenger deleted