###Calculate Distance
POST http://localhost:9080/trips/position
Content-Type: application/json

{
  "origin":{
    "latitude": 34.32,
    "longitude": 24.09
  },
  "destination":{
    "latitude": 41.14,
    "longitude": 67.42
  }
}