### Calculate Distance
GET http://localhost:9080/trips/position?originLatitude=20.05&originLongitude=40.05&destLatitude=35.06&destLongitude=55.06

//Reponse 2224.788

### Calculate Distance
GET http://localhost:9080/trips/position?originLatitude=10.05&originLongitude=44.05&destLatitude=25.06&destLongitude=75.06

//Reponse 3672.612