### Create user
POST http://localhost:9002/users
Content-Type: application/json

{
  "email": "1@Car",
  "first_name": "1",
  "last_name": "1"
}

### Create user 2
POST http://localhost:9002/users
Content-Type: application/json

{
  "email": "2@Car",
  "first_name": "2",
  "last_name": "2"
}

### Create user 3
POST http://localhost:9002/users
Content-Type: application/json

{
  "email": "3@Car",
  "first_name": "2",
  "last_name": "2"
}

### Get user by id
GET http://localhost:9002/users/3