### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "ouffihg@gmail.com",
  "firstname": "rayan",
  "lastname": "bka",
  "password": "123"
}

### Connect user
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "oui@gmail.com",
  "password": "1234"
}

> {%
client.global.set("token", response.body);
%}


### Get user by email

GET http://localhost:8080/users?email=oui@gmail.com

### Get user by id

GET http://localhost:8080/users/19

### update user password

PUT http://localhost:8080/users
Content-Type: application/json
Authorization: {{token}}

{
  "email": "oui@gmail.com",
  "password": "1234"
}

### update user

PUT http://localhost:8080/users/19
Content-Type: application/json
Authorization: {{token}}

{
  "id": 19,
  "email": "oui@gmail.com",
  "firstname": "rayan",
  "lastname": "bke"
}
### Delete one
DELETE http://localhost:9090/users/19
Authorization: {{token}}
