### Connect user
POST http://localhost:8080/auth
Content-Type: application/json

{
  "email": "zoe@gmail.com",
  "password": "123456"
}

> {%
client.global.set("token", response.body);
%}

### Create Trips
POST http://localhost:8080/trips
Content-Type: application/json
Authorization: {{token}}

{
  "origin": {
    "latitude": 50.849372,
    "longitude": 4.451009
  },
  "destination": {
    "latitude": 50.849372,
    "longitude": 4.451009
  },
  "departure": "2022-10-24",
  "driver_id": 1,
  "available_seating": 8
}


### Read one
GET http://localhost:8080/trips/1

### Read all
GET http://localhost:8080/trips

### Delete one
DELETE http://localhost:8080/trips/1

### Read all of driver
GET http://localhost:8080/users/2/driver
Authorization: {{token}}

### Delete all trips of driver
DELETE http://localhost:8080/trips/driver/2